import type { QikinkProduct } from "./types";

// Fixture catalog covering every category in the brief, so the storefront,
// bundles, and admin views are all populated before real Qikink credentials
// exist. Shape matches QikinkProduct exactly — swapping QIKINK_USE_MOCK to
// "false" with real credentials requires no code change downstream.

const img = (seed: string, alt: string, primary = false) => ({
  url: `https://picsum.photos/seed/${seed}/1200/1500`,
  is_primary: primary,
  alt_text: alt,
});

const SIZES = ["S", "M", "L", "XL", "XXL"];

function variants(skuPrefix: string, price: number, mrp: number, stockBySize: Partial<Record<string, number>> = {}) {
  return SIZES.map((size, i) => ({
    variant_id: `${skuPrefix}-${size}`,
    sku: `${skuPrefix}-${size}`,
    size,
    color: "Black",
    price,
    mrp,
    quantity: stockBySize[size] ?? [12, 20, 25, 15, 6][i],
    weight_grams: 220,
  }));
}

export const MOCK_QIKINK_PRODUCTS: QikinkProduct[] = [
  {
    product_id: "qk_ovt_001",
    name: "Blackout Oversized Tee",
    description:
      "Heavyweight 240 GSM cotton oversized tee with a boxy drop-shoulder fit. Built for streetwear, not gym mirrors.",
    category: "Men's Oversized T-Shirts",
    fabric: "240 GSM 100% Combed Cotton",
    care_instructions: "Machine wash cold, inside out. Do not bleach. Tumble dry low.",
    base_price: 899,
    mrp: 1299,
    images: [img("ovt001a", "Blackout Oversized Tee front", true), img("ovt001b", "Blackout Oversized Tee back")],
    variants: variants("OVT-BLACKOUT", 899, 1299),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_ovt_002",
    name: "Concrete Grey Oversized Tee",
    description: "Washed grey oversized tee with dropped shoulders and ribbed collar.",
    category: "Men's Oversized T-Shirts",
    fabric: "240 GSM 100% Combed Cotton",
    care_instructions: "Machine wash cold, inside out.",
    base_price: 899,
    mrp: 1299,
    images: [img("ovt002a", "Concrete Grey Tee front", true), img("ovt002b", "Concrete Grey Tee lifestyle")],
    variants: variants("OVT-CONCRETE", 899, 1299),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_gym_001",
    name: "Performance Gym Tee — Dry Fit",
    description: "Moisture-wicking dry-fit gym tee, athletic taper, breathable mesh underarm panels.",
    category: "Men's Gym T-Shirts",
    fabric: "Polyester-Spandex Dry Fit",
    care_instructions: "Machine wash cold. Do not iron print.",
    base_price: 699,
    mrp: 999,
    images: [img("gym001a", "Performance Gym Tee front", true)],
    variants: variants("GYM-DRYFIT", 699, 999),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_ovs_001",
    name: "Heavy Cotton Oversized Shirt — Olive",
    description: "Boxy oversized shirt in heavy cotton twill, dropped shoulders, single chest pocket.",
    category: "Men's Oversized Shirts",
    fabric: "Cotton Twill",
    care_instructions: "Machine wash cold, hang dry.",
    base_price: 1499,
    mrp: 1999,
    images: [img("ovs001a", "Oversized Shirt Olive front", true)],
    variants: variants("OVS-OLIVE", 1499, 1999),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_wovt_001",
    name: "Women's Oversized Tee — Dusty Pink",
    description: "Cropped-length oversized tee, soft-washed cotton, boxy silhouette.",
    category: "Women's Oversized T-Shirts",
    fabric: "220 GSM Combed Cotton",
    care_instructions: "Machine wash cold, inside out.",
    base_price: 799,
    mrp: 1099,
    images: [img("wovt001a", "Women's Oversized Tee front", true)],
    variants: variants("WOVT-PINK", 799, 1099),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_wgym_001",
    name: "Women's Gym Tee — Seamless",
    description: "Seamless knit gym tee with four-way stretch.",
    category: "Women's Gym T-Shirts",
    fabric: "Nylon-Spandex Seamless Knit",
    care_instructions: "Machine wash cold.",
    base_price: 749,
    mrp: 1099,
    images: [img("wgym001a", "Women's Gym Tee front", true)],
    variants: variants("WGYM-SEAM", 749, 1099),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_cap_001",
    name: "Aneem Signature Cap — Black",
    description: "Structured 6-panel cap with embroidered logo, adjustable strap.",
    category: "Caps",
    base_price: 499,
    mrp: 699,
    images: [img("cap001a", "Aneem Cap Black", true)],
    variants: [{ variant_id: "CAP-BLK-OS", sku: "CAP-BLK-OS", size: "One Size", color: "Black", price: 499, mrp: 699, quantity: 40 }],
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_bottle_001",
    name: "Aneem Steel Bottle — 750ml",
    description: "Double-wall insulated stainless steel bottle, keeps cold 24h.",
    category: "Bottles",
    base_price: 599,
    mrp: 899,
    images: [img("bottle001a", "Aneem Steel Bottle", true)],
    variants: [{ variant_id: "BTL-750-BLK", sku: "BTL-750-BLK", size: "750ml", color: "Black", price: 599, mrp: 899, quantity: 35 }],
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_tumbler_001",
    name: "Aneem Travel Tumbler — 500ml",
    description: "Leak-proof travel tumbler with matte finish.",
    category: "Tumblers",
    base_price: 549,
    mrp: 799,
    images: [img("tumbler001a", "Aneem Tumbler", true)],
    variants: [{ variant_id: "TMB-500-BLK", sku: "TMB-500-BLK", size: "500ml", color: "Black", price: 549, mrp: 799, quantity: 30 }],
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_hoodie_001",
    name: "Oversized Fleece Hoodie — Jet Black",
    description: "400 GSM heavyweight fleece hoodie, oversized fit, kangaroo pocket.",
    category: "Hoodies",
    fabric: "400 GSM Cotton Fleece",
    care_instructions: "Machine wash cold, do not tumble dry.",
    base_price: 1799,
    mrp: 2499,
    images: [img("hoodie001a", "Oversized Hoodie front", true), img("hoodie001b", "Oversized Hoodie lifestyle")],
    variants: variants("HOOD-JETBLK", 1799, 2499),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_sweat_001",
    name: "Essential Oversized Sweatshirt — Charcoal",
    description: "Mid-weight oversized sweatshirt with ribbed hem and cuffs.",
    category: "Sweatshirts",
    fabric: "320 GSM Cotton Fleece",
    care_instructions: "Machine wash cold.",
    base_price: 1399,
    mrp: 1899,
    images: [img("sweat001a", "Oversized Sweatshirt front", true)],
    variants: variants("SWT-CHAR", 1399, 1899),
    status: "active",
    updated_at: new Date().toISOString(),
  },
  {
    product_id: "qk_jacket_001",
    name: "Coach Jacket — Windbreaker",
    description: "Lightweight water-resistant coach jacket with snap buttons.",
    category: "Jackets",
    fabric: "Polyester Ripstop",
    care_instructions: "Machine wash cold, hang dry.",
    base_price: 2199,
    mrp: 2999,
    images: [img("jacket001a", "Coach Jacket front", true)],
    variants: variants("JKT-WIND", 2199, 2999),
    status: "active",
    updated_at: new Date().toISOString(),
  },
];
