name: Upload Artifact Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create a test file
        run: echo "Hello GitHub Actions!" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: hello.txt
