name: Fetch Orders and Generate Excel

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests openpyxl pandas

      - name: Run order fetch script
        env:
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          QIKIN_API_TOKEN: ${{ secrets.QIKIN_API_TOKEN }}
        run: python scripts/fetch_and_generate_excel.py

      - name: Upload Excel as artifact
        uses: actions/upload-artifact@v2
        with:
          name: order-report
          path: order_report.xlsx
